bukuwajah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import profil.urls as profil 
import cari_mahasiswa.urls as cari_mahasiswa
import login_status.urls as login_status
import riwayat.urls as riwayat

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(login_status, namespace='login-status')),
    url(r'^profil/', include(profil,namespace='profil')),

    url(r'^cari-mahasiswa/', include(cari_mahasiswa, namespace = 'cari-mahasiswa')),

    url(r'^riwayat/', include(riwayat,namespace='riwayat')),

]

login_status/urls.py
from django.conf.urls import url
from .views import status, post_status, login, company_page
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', company_page, name='company-page'),
    url(r'^login/$', login, name='login'),
    
    url(r'^status/$', status, name='status'),
    url(r'^post_status', post_status, name='post-status'),

    # custom auth
    url(r'^auth_login/$', auth_login, name='auth_login'),
    url(r'^auth_logout/$', auth_logout, name='auth_logout'),

]
    

profil/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile-edit/$', profile_edit, name='profile-edit'),
    url(r'^update-profile/$', update_user_profile, name='update-profile'),
    url(r'^update-keahlian/$', update_user_keahlian, name='update-keahlian'),
    url(r'^get-keahlian/$', get_keahlian_json, name='get-keahlian'),
    url(r'^delete-keahlian/$', delete_user_keahlian, name='delete-keahlian'),
]

login_status/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    identity_number = models.CharField(max_length=20)
    name = models.CharField(max_length=200)

class Status(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

login_status/forms.py
from django import forms

class Status_Form(forms.Form):
    status = forms.CharField(required=True)

login_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import User, Status
from .forms import Status_Form
from riwayat.api_riwayat import get_riwayat
from profil.models import UserLinkedIn, KeahlianUser
from riwayat.views import hidden_or_not
from cari_mahasiswa.views import mahasiswa_list, mahasiswa_listKeahlian

# Create your views here.
response = {'author' : 'Aldi Hilman Ramadhani', 'riwayat' : get_riwayat()}
def login(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('login-status:status'))
    else:
        response['is_login'] = False
        html = 'login/login.html'
        return render(request, html, response)
        
def status(request):
    if 'user_login' in request.session:
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username)
        response['all_status'] = Status.objects.filter(user_id=response['user'].id)
        response['user_linkedin'] = UserLinkedIn.objects.filter(user_id=response['user'].id).first()
        response['keahlian_user'] = KeahlianUser.objects.filter(user_linkedin=response['user_linkedin'])
        response['status_count'] = response['all_status'].count()
        response['status_form'] = Status_Form
        response['flag'] = hidden_or_not(request)
        response['mahasiswa_list'] = mahasiswa_list(request)
        response['mahasiswa_listKeahlian'] = mahasiswa_listKeahlian(request)
        html = 'dashboard/base.html'
        return render(request, html, response)

    response['is_login'] = False
    html = 'login/login.html'
    return render(request, html, response)
    
def post_status(request):
    form = Status_Form(request.POST or None)
    if 'user_login' in request.session and request.method == 'POST' and form.is_valid():
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        status_message = request.POST['status']
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username)
        new_status = Status.objects.create(description=status_message, user=response['user'])
        return HttpResponseRedirect(reverse('login-status:status'))
        
    response['is_login'] = False
    html = 'login/login.html'
    return render(request, html, response)
    
def company_page(request):
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('login-status:status'))
    else:
        response['is_login'] = False
        html = 'login/company.html'
        return render(request, html, response)

login_status/templates/dashboard/base.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}
<!-- Content Here -->
<div class="pojok-kanan">
</div>
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2> Selamat Datang, {{ user.name }} </h2>
    </div>
    <div class="panel-body">
        {% if user_linkedin.user_image %}
            <img src="{{ user_linkedin.user_image }}" class="img-circle" height="150" width="150" align="left"></img>
        {% else %}
            <img src="https://image.ibb.co/ew4oAG/blank_Profile.png" class="img-circle" height="150" width="150" align="left"></img>
        {% endif %}
        <a href="{% url 'login-status:login' %}" style="text-align:left;float:up;">
            <button type="button" class="btn btn-default">Lihat Forum (Unavailable)</button>
        </a>
        <h4 style="text-align:right;float:up;">Jumlah Status : {{ status_count }}</h4>

        <a href="{% url 'profil:index' %}" style="text-align:left;float:down;">
            <button type="button" class="btn btn-default">Edit Profile</button>
        </a>
        <h4 style="text-align:right;float:down;">{{ user_linkedin.user_headline }}</h4>
    </div>
</div>
    
    <ul class="nav nav-tabs" role="tablist">
        <li class="active">
          <a href="#status"  data-toggle="tab"> Status </a>
        </li>
        <li>
            <a href="#profile" data-toggle="tab"> Profile </a>
        </li>
        <li>
            <a href="#riwayat"  data-toggle="tab"> Riwayat </a>
        </li>
        <li>
            <a href="#teman"  data-toggle="tab"> Teman </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="status">
            {% include 'status/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
            {% include 'profil/profil_mini.html' %}
        </div>
        <div role="tabpanel" class="tab-pane" id="riwayat">
            {% include 'riwayat/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane" id="teman">
            {% include 'cari_mahasiswa/mahasiswa.html' %}
            
        </div>
    </div>
</div>
{% endblock %}