bukuwajah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import profil.urls as profil 
import cari_mahasiswa.urls as cari_mahasiswa
import login_status.urls as login_status
import riwayat.urls as riwayat

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(login_status, namespace='login-status')),
    url(r'^profil/', include(profil,namespace='profil')),

    url(r'^cari-mahasiswa/', include(cari_mahasiswa, namespace = 'cari-mahasiswa')),

    url(r'^riwayat/', include(riwayat,namespace='riwayat')),

]

login_status/urls.py
from django.conf.urls import url
from .views import status, post_status, login, company_page
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', company_page, name='company-page'),
    url(r'^login/$', login, name='login'),
    
    url(r'^status/$', status, name='status'),
    url(r'^post_status', post_status, name='post-status'),

    # custom auth
    url(r'^auth_login/$', auth_login, name='auth_login'),
    url(r'^auth_logout/$', auth_logout, name='auth_logout'),

]
    

profil/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile-edit/$', profile_edit, name='profile-edit'),
    url(r'^update-profile/$', update_user_profile, name='update-profile'),
    url(r'^update-keahlian/$', update_user_keahlian, name='update-keahlian'),
    url(r'^get-keahlian/$', get_keahlian_json, name='get-keahlian'),
    url(r'^delete-keahlian/$', delete_user_keahlian, name='delete-keahlian'),
]

login_status/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    identity_number = models.CharField(max_length=20)
    name = models.CharField(max_length=200)

class Status(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

login_status/forms.py
from django import forms

class Status_Form(forms.Form):
    status = forms.CharField(required=True)

login_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import User, Status
from .forms import Status_Form
from riwayat.api_riwayat import get_riwayat
from profil.models import UserLinkedIn, KeahlianUser
from riwayat.views import hidden_or_not
from cari_mahasiswa.views import mahasiswa_list, mahasiswa_listKeahlian

# Create your views here.
response = {'author' : 'Aldi Hilman Ramadhani', 'riwayat' : get_riwayat()}
def login(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('login-status:status'))
    else:
        response['is_login'] = False
        html = 'login/login.html'
        return render(request, html, response)
        
def status(request):
    if 'user_login' in request.session:
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username)
        response['all_status'] = Status.objects.filter(user_id=response['user'].id)
        response['user_linkedin'] = UserLinkedIn.objects.filter(user_id=response['user'].id).first()
        response['keahlian_user'] = KeahlianUser.objects.filter(user_linkedin=response['user_linkedin'])
        response['status_count'] = response['all_status'].count()
        response['status_form'] = Status_Form
        response['flag'] = hidden_or_not(request)
        response['mahasiswa_list'] = mahasiswa_list(request)
        response['mahasiswa_listKeahlian'] = mahasiswa_listKeahlian(request)
        html = 'dashboard/base.html'
        return render(request, html, response)

    response['is_login'] = False
    html = 'login/login.html'
    return render(request, html, response)
    
def post_status(request):
    form = Status_Form(request.POST or None)
    if 'user_login' in request.session and request.method == 'POST' and form.is_valid():
        response['is_login'] = True
        
        username = request.session['user_login']
        kode_identitas = request.session['kode_identitas']
        status_message = request.POST['status']
        response['user'], is_login = User.objects.get_or_create(identity_number=kode_identitas, name=username)
        new_status = Status.objects.create(description=status_message, user=response['user'])
        return HttpResponseRedirect(reverse('login-status:status'))
        
    response['is_login'] = False
    html = 'login/login.html'
    return render(request, html, response)
    
def company_page(request):
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('login-status:status'))
    else:
        response['is_login'] = False
        html = 'login/company.html'
        return render(request, html, response)

login_status/templates/login/company.html
{% extends "layout/base.html" %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3> Sumsang (merk HP) </h3>
        </div>
        <div class="panel-body">
              <img src="https://vignette.wikia.nocookie.net/phineasandferb/images/7/7a/Doofenshmirtz_Evil_Inc._building.jpg/revision/latest?cb=20090917225901" class="img-circle" height="100" width="100" align="left"></img>
            <h4> Perusahaan kami sedang ingin hire 1000 Great Engineer. Lowongan terbuka untuk : </h4>
            <h4> 1. Software Engineer </h4>
            <h4> 2. System Engineer </h4>
        </div>
        
        <div class="container">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <h3> Sang Bijaksana </h3>
              </div>
              <div class="panel-body">
                <img src="http://corecanvas.s3.amazonaws.com/theonering-0188db0e/gallery/original/gandalf020830a.jpg" class="img-circle" height="100" width="100" align="left"></img>
                <h4>Hi. Mas, minta HP bole gak?</h4>
              </div>
              
              <div class="panel-heading">
                  <h3> Sumsang (merk HP) </h3>
              </div>
              <div class="panel-body">
                <img src="https://vignette.wikia.nocookie.net/phineasandferb/images/7/7a/Doofenshmirtz_Evil_Inc._building.jpg/revision/latest?cb=20090917225901" class="img-circle" height="100" width="100" align="left"></img>
                <h4> Ya kagaklah </h4>
              </div>
            </div>
        </div>
        
    </div>
</div>
<div align="center">
  <a href="{% url 'login-status:login' %}">
      <button type="button" class="btn btn-warning">SSO Login</button>
  </a>
  <a>
    <img src="https://content.linkedin.com/content/dam/developer/global/en_US/site/img/signin-button.png">
  </a>
<div>
{% endblock %}

login_status/templates/login/login.html
{% extends "layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <h2 id="landing-page" hidden>{{landing_page}}</h2>
            <form action="{% url 'login-status:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" id="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}